module.exports = StrokeConstants =
	HORIZONTAL_STROKE: 1
	BACK_SLASH_STROKE: 2
	VERTICAL_STROKE: 3
	FORWARD_SLASH_STROKE: 4
	REVERSE_HORIZONTAL_STROKE: 5
	REVERSE_BACK_SLASH_STROKE: 6
	REVERSE_VERTICAL_STROKE: 7
	REVERSE_FORWARD_SLASH_STROKE: 8